include:
  - docker-compose.yml
services:
  capture-backend:
    depends_on:
      - ftw
    image: utils/tcpdump
    network_mode: service:backend

  capture-crs-apache:
    depends_on:
      - ftw
    image: utils/tcpdump
    network_mode: service:crs-apache

  capture-ftw:
    depends_on:
      - ftw
    image: utils/tcpdump
    network_mode: service:ftw
  