ARG BASE_NGINX_TAG=stable-alpine
ARG MODSECURITY_CRS_TAG=4-nginx-202607160307
ARG UBUNTU_VERSION=22.04

FROM nginxinc/nginx-unprivileged:${BASE_NGINX_TAG} AS base_nginx

FROM owasp/modsecurity-crs:${MODSECURITY_CRS_TAG} AS base_modsecurity

FROM ubuntu:${UBUNTU_VERSION} AS crs_release

ARG UID=101
ARG GID=101

RUN set -x \
# create nginx user/group first, to be consistent throughout docker variants
    && groupadd --system --gid $GID nginx || true \
    && useradd --system --gid nginx --no-create-home --home /nonexistent --comment "nginx user" --shell /bin/false --uid $UID nginx || true

ARG LUAJIT_DEB_VERSION=2.1.20260717-1hn1ubuntu22.04
ARG MODSECURITY_DEB_VERSION=3.0.16-1hn1ubuntu22.04
ARG NGINX_DEB_VERSION=1.30.4+mod.1-1hn1ubuntu22.04
ARG NGINX_DEB_VERSION_URL_ENCODED=1.30.4%2Bmod.1-1hn1ubuntu22.04

RUN set -eux; \
    apt-get update; \
    # gettext-base is needed for envsubst command.
    DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends \
        ca-certificates \
        curl \
        gnupg \
        gettext-base; \
    mkdir /tmp/deb; \
    curl -sSL https://github.com/hnakamur/openresty-luajit-deb-docker/releases/download/${LUAJIT_DEB_VERSION}/openresty-luajit-${LUAJIT_DEB_VERSION}.tar.gz \
        | tar zx --strip-components=2 -C /tmp/deb; \
    curl -sSL https://github.com/hnakamur/modsecurity-deb-docker/releases/download/${MODSECURITY_DEB_VERSION}/modsecurity-${MODSECURITY_DEB_VERSION}.tar.gz \
        | tar zx --strip-components=2 -C /tmp/deb; \
    curl -sSL https://github.com/hnakamur/nginx-deb-docker/releases/download/${NGINX_DEB_VERSION_URL_ENCODED}/nginx-${NGINX_DEB_VERSION}.tar.gz \
        | tar zx --strip-components=2 -C /tmp/deb; \
    DEBIAN_FRONTEND=noninteractive apt-get -y install \
        /tmp/deb/libluajit-5.1-2_*.deb \
        /tmp/deb/libluajit-5.1-common_*.deb \
        /tmp/deb/luajit_*.deb \
        /tmp/deb/libmodsecurity3_*.deb \
        /tmp/deb/nginx_*.deb; \
    rm -rf /tmp/deb /var/lib/apt/lists/* /var/cache/apt/archives/*

COPY --from=base_nginx /docker-entrypoint.sh /
COPY --from=base_nginx /docker-entrypoint.d/ /docker-entrypoint.d/

COPY --from=base_modsecurity /etc/nginx/templates/ /etc/nginx/templates/
COPY --from=base_modsecurity /docker-entrypoint.d/ /docker-entrypoint.d/
COPY --from=base_modsecurity /usr/local/bin/check-low-port /usr/local/bin/generate-certificate /usr/local/bin/healthcheck /usr/local/bin/

RUN set -eux; \
    mkdir /opt/owasp-crs /etc/modsecurity.d /etc/nginx/ssl; \
    chown nginx:nginx /opt/owasp-crs; \
    curl -sSL https://raw.githubusercontent.com/owasp-modsecurity/ModSecurity/v3/master/unicode.mapping \
         -o /etc/modsecurity.d/unicode.mapping; \
    # Comment out the SecDisableBackendCompression option since it is not supported in V3
    sed -i 's/^\(SecDisableBackendCompression .*\)/# \1/' /etc/nginx/templates/modsecurity.d/modsecurity-override.conf.template; \
    ln -sv /opt/owasp-crs /etc/modsecurity.d/; \
    mkdir -p /var/log/modsecurity/audit; \
    chown nginx:nginx \
        /var/log/modsecurity/audit \
        /opt/owasp-crs \
        /etc/modsecurity.d

USER nginx

WORKDIR /tmp/sources

ARG CRS_RELEASE=4.28.0
RUN set -eux; \
    curl -sSL https://github.com/coreruleset/coreruleset/releases/download/v${CRS_RELEASE}/coreruleset-${CRS_RELEASE}-minimal.tar.gz -o v${CRS_RELEASE}-minimal.tar.gz; \
    curl -sSL https://github.com/coreruleset/coreruleset/releases/download/v${CRS_RELEASE}/coreruleset-${CRS_RELEASE}-minimal.tar.gz.asc -o coreruleset-${CRS_RELEASE}-minimal.tar.gz.asc; \
    export GNUPGHOME=$(mktemp -d); \
    gpg --fetch-key https://coreruleset.org/security.asc; \
    gpg --verify coreruleset-${CRS_RELEASE}-minimal.tar.gz.asc v${CRS_RELEASE}-minimal.tar.gz; \
    rm -r ${GNUPGHOME}; \
    tar -zxf v${CRS_RELEASE}-minimal.tar.gz --strip-components=1 -C /opt/owasp-crs; \
    rm -f v${CRS_RELEASE}-minimal.tar.gz coreruleset-${CRS_RELEASE}-minimal.tar.gz.asc; \
    mv -v /opt/owasp-crs/crs-setup.conf.example /opt/owasp-crs/crs-setup.conf; \
    mkdir -p /tmp/modsecurity/data \
        /tmp/modsecurity/upload \
        /tmp/modsecurity/tmp

ARG NGINX_HOME="/etc/nginx"
ENV NGINX_HOME="${NGINX_HOME}"

WORKDIR "${NGINX_HOME}"

ENV \
    ACCESSLOG=/var/log/nginx/access.log \
    BACKEND=http://localhost:80 \
    CLIENT_BODY_TIMEOUT=10s \
    CORS_HEADER_403_ALLOW_ORIGIN="*" \
    CORS_HEADER_403_ALLOW_METHODS="GET, POST, PUT, DELETE, OPTIONS" \
    CORS_HEADER_403_CONTENT_TYPE="text/html" \
    CORS_HEADER_403_MAX_AGE=3600 \
    CORS_HEADER_ACCESS_CONTROL_ALLOW_HEADERS="*" \
    ERRORLOG=/var/log/nginx/error.log \
    HTTP2=on \
    KEEPALIVE_TIMEOUT=60s \
    LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib \
    LOGLEVEL=warn \
    METRICS_ALLOW_FROM='127.0.0.0/24' \
    METRICS_DENY_FROM='all' \
    METRICSLOG=/dev/null \
    MODSEC_ARGUMENT_SEPARATOR="&" \
    MODSEC_ARGUMENTS_LIMIT=1000 \
    MODSEC_AUDIT_ENGINE="RelevantOnly" \
    MODSEC_AUDIT_LOG=/dev/stdout \
    MODSEC_AUDIT_LOG_FORMAT=JSON \
    MODSEC_AUDIT_LOG_PARTS='ABIJDEFHZ' \
    MODSEC_AUDIT_LOG_RELEVANT_STATUS="^(?:5|4(?!04))" \
    MODSEC_AUDIT_LOG_TYPE=Serial \
    MODSEC_COOKIE_FORMAT=0 \
    MODSEC_AUDIT_STORAGE_DIR=/var/log/modsecurity/audit/ \
    MODSEC_DATA_DIR=/tmp/modsecurity/data \
    MODSEC_DEBUG_LOG=/dev/null \
    MODSEC_DEBUG_LOGLEVEL=0 \
    MODSEC_DEFAULT_PHASE1_ACTION="phase:1,pass,log,tag:'\${MODSEC_TAG}'" \
    MODSEC_DEFAULT_PHASE2_ACTION="phase:2,pass,log,tag:'\${MODSEC_TAG}'" \
    MODSEC_DISABLE_BACKEND_COMPRESSION="Off" \
    MODSEC_PCRE_MATCH_LIMIT=100000 \
    MODSEC_PCRE_MATCH_LIMIT_RECURSION=100000 \
    MODSEC_REQ_BODY_ACCESS=on \
    MODSEC_REQ_BODY_JSON_DEPTH_LIMIT=512 \
    MODSEC_REQ_BODY_LIMIT=13107200 \
    MODSEC_REQ_BODY_LIMIT_ACTION="Reject" \
    MODSEC_REQ_BODY_NOFILES_LIMIT=131072 \
    MODSEC_RESP_BODY_ACCESS=on \
    MODSEC_RESP_BODY_LIMIT=1048576 \
    MODSEC_RESP_BODY_LIMIT_ACTION="ProcessPartial" \
    MODSEC_RESP_BODY_MIMETYPE="text/plain text/html text/xml" \
    MODSEC_RULE_ENGINE=on \
    MODSEC_STATUS_ENGINE="Off" \
    MODSEC_TAG=modsecurity \
    MODSEC_TMP_DIR=/tmp/modsecurity/tmp \
    MODSEC_TMP_SAVE_UPLOADED_FILES="on" \
    MODSEC_UNICODE_MAPPING=20127 \
    MODSEC_UPLOAD_DIR=/tmp/modsecurity/upload \
    MODSEC_UPLOAD_FILE_MODE=0600 \
    MODSEC_UPLOAD_KEEP_FILES=Off \
    NGINX_ALWAYS_TLS_REDIRECT=off \
    NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx \
    NGINX_PORT_IN_REDIRECT=off \
    NGINX_X_FORWARDED_PORT='$server_port' \
    NGINX_X_FORWARDED_PROTO='$scheme' \
    PORT=8080 \
    PROXY_SSL_CERT_FILE=/etc/nginx/conf/proxy.crt \
    PROXY_SSL_CERT_KEY_FILE=/etc/nginx/conf/proxy.key \
    PROXY_SSL_CIPHERS="ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384" \
    PROXY_SSL=off \
    PROXY_SSL_PROTOCOLS="TLSv1.2 TLSv1.3" \
    PROXY_SSL_VERIFY_DEPTH=1 \
    PROXY_SSL_VERIFY=off \
    PROXY_TIMEOUT=60s \
    REAL_IP_HEADER="X-REAL-IP" \
    REAL_IP_PROXY_HEADER="X-REAL-IP" \
    REAL_IP_RECURSIVE="on" \
    RESOLVERS= \
    RESOLVER_CONFIG="valid=5s"\
    SERVER_NAME=localhost \
    SERVER_TOKENS=off \
    SET_REAL_IP_FROM="127.0.0.1" \
    SSL_CERT_FILE=/etc/nginx/conf/server.crt \
    SSL_CERT_KEY_FILE=/etc/nginx/conf/server.key \
    SSL_CIPHERS="ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384" \
    SSL_DH_BITS=2048 \
    SSL_OCSP_STAPLING=on \
    SSL_PORT=8443 \
    SSL_PREFER_CIPHERS=off \
    SSL_PROTOCOLS="TLSv1.2 TLSv1.3" \
    SSL_VERIFY_DEPTH=1 \
    SSL_VERIFY=off \
    WORKER_CONNECTIONS=1024 \
    # CRS specific variables
    ANOMALY_INBOUND=5 \
    ANOMALY_OUTBOUND=4 \
    BLOCKING_PARANOIA=1

HEALTHCHECK CMD /usr/local/bin/healthcheck

ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 8080

STOPSIGNAL SIGQUIT

USER $UID

CMD ["nginx", "-g", "daemon off;"]
