# This docker-compose file runs tests using
# ftw, owasp/modsecurity-crs, and albedo.
services:
  backend:
    image: ghcr.io/coreruleset/albedo:0.2.0
    command: ["--port", "8081"]
    ports:
      - 8081:8081

  crs-apache:
    depends_on:
      - backend
    image: owasp/modsecurity-crs:apache
    ports:
      - "8080:8080"
    environment:
      SERVERNAME: localhost
      BACKEND: http://backend:8081
      APACHE_LOGFORMAT: 'time:%{end:%y-%m-%dT%H:%M:%S}t.%{msec_frac}t%{%z}t\treq:%r\tstatus:%>s\treq_time_us:%D\tuser_agent:%{User-agent}i\tx_crs_test:%{X-CRS-Test}i'
      MODSEC_DEBUG_LOGLEVEL: 0
      MODSEC_DEBUG_LOG: /var/log/apache2/modsec_debug.log
      MODSEC_AUDIT_LOG: /var/log/apache2/modsec_audit.log
      # CRS Variables for testing using ftw
      MODSEC_RULE_ENGINE: DetectionOnly
      PARANOIA: 4
      BLOCKING_PARANOIA: 4
      ANOMALY_INBOUND: 5
      ANOMALY_OUTBOUND: 4
      REPORTING_LEVEL: 4
      VALIDATE_UTF8_ENCODING: 1
      MAX_NUM_ARGS: 255
      ARG_NAME_LENGTH: 100
      ARG_LENGTH: 400
      TOTAL_ARG_LENGTH: 64000
      MAX_FILE_SIZE: 64100
      COMBINED_FILE_SIZES: 65535
      CRS_ENABLE_TEST_MARKER: 1
    volumes:
      # Volumes for sharing ModSecurity log files to ftw
      - apache2_log:/var/log/apache2:rw

  ftw:
    depends_on:
      - crs-apache
    build:
      context: .
      dockerfile: ./Dockerfile.ftw
    environment:
      - FTW_CLOUDMODE
      - FTW_INCLUDE
      - FTW_DEBUG
    volumes:
      - apache2_log:/var/log/apache2:ro
volumes:
  apache2_log:
